name:                aoc2022
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/aoc2022#readme
license:             BSD3
author:              Morten Kolstad
maintainer:          example@example.com
copyright:           2021 Morten Kolstad
category:            Web
extra-source-files:
- README.md

default-extensions:
 - OverloadedStrings
 - ViewPatterns
 - OverloadedRecordDot
 - DuplicateRecordFields
 - NoFieldSelectors

language: GHC2021

dependencies:
  - base >= 4.16 && < 5
  - lens
  - linear
  - bytestring
  - text
  - stringsearch
  - megaparsec
  - transformers
  - mtl
  - comonad
  - containers
  - ordered-containers
  - unordered-containers
  - extra
  - safe
  - split
  - groupBy
  - memoize
  - haskell-src-meta
  - template-haskell
  - vector
  - array
  - digits
  - fgl
  - HUnit

library:
    source-dirs: src/lib
    when:
      - condition: false
        other-modules: Paths_aoc2022

executables:
  app:
    source-dirs:      src/app
    main:             Main.hs
    dependencies:
      - aoc2022
      - timeit
      - http-conduit
      - dotenv
      - optparse-applicative
    when:
      - condition: false
        other-modules: Paths_app